-- 更新 MatchWagers 表的欄位備註
ALTER TABLE MatchWagers 
MODIFY COLUMN WID INT AUTO_INCREMENT COMMENT '委託單ID',
MODIFY COLUMN WD_ID INT NOT NULL COMMENT '出款單號',
MODIFY COLUMN WD_Amount SMALLINT NOT NULL COMMENT '出款單金額',
MODIFY COLUMN WD_Account VARCHAR(15) NOT NULL COMMENT '出款單帳戶',
MODIFY COLUMN WD_Date DATE NOT NULL COMMENT '出款單日期',
MODIFY COLUMN WD_DateTime DATETIME NOT NULL COMMENT '出款單新增時間',
MODIFY COLUMN State ENUM('Order', 'Rejected', 'Matching', 'Success', 'Cancel') NOT NULL DEFAULT 'Order' COMMENT '狀態',
MODIFY COLUMN Reserve_UserID INT DEFAULT NULL COMMENT '預約入款會員ID',
MODIFY COLUMN Reserve_DateTime DATETIME DEFAULT NULL COMMENT '會員預約時間',
MODIFY COLUMN DEP_ID INT DEFAULT NULL COMMENT '入款單號',
MODIFY COLUMN DEP_Amount SMALLINT DEFAULT NULL COMMENT '入款單金額',
MODIFY COLUMN Finish_DateTime DATETIME DEFAULT NULL COMMENT '完成時間'; 