services:
  mysql-master:
    image: mysql:8.0
    platform: linux/amd64
    container_name: match_mysql_master
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_master_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
      - ./database/mysql-master.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - match_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 5s
      start_period: 30s

  mysql-slave:
    image: mysql:8.0
    platform: linux/amd64
    container_name: match_mysql_slave
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - mysql_slave_data:/var/lib/mysql
      - ./database/mysql-slave.cnf:/etc/mysql/conf.d/mysql.cnf
    depends_on:
      mysql-master:
        condition: service_healthy
    networks:
      - match_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
      interval: 5s
      start_period: 30s

  match-api:
    build: .
    container_name: match_api
    depends_on:
      mysql-master:
        condition: service_healthy
    ports:
      - "${API_PORT}:8080"
    environment:
      DB_HOST: mysql-master
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_NAME: ${MYSQL_DATABASE}
      DB_SLAVE_HOST: mysql-slave
      DB_SLAVE_PORT: 3306
      GIN_MODE: ${GIN_MODE}
    networks:
      - match_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      timeout: 10s
      retries: 5
      interval: 5s
      start_period: 30s
    restart: unless-stopped

  phpmyadmin-master:
    image: phpmyadmin/phpmyadmin:5.2
    platform: linux/amd64
    container_name: match_phpmyadmin_master
    depends_on:
      mysql-master:
        condition: service_healthy
    environment:
      PMA_HOST: mysql-master
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    ports:
      - "8081:80"
    networks:
      - match_network
    restart: unless-stopped

  phpmyadmin-slave:
    image: phpmyadmin/phpmyadmin:5.2
    platform: linux/amd64
    container_name: match_phpmyadmin_slave
    depends_on:
      mysql-slave:
        condition: service_healthy
    environment:
      PMA_HOST: mysql-slave
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 300M
    ports:
      - "8082:80"
    networks:
      - match_network
    restart: unless-stopped

volumes:
  mysql_master_data:
  mysql_slave_data:

networks:
  match_network:
    driver: bridge 